apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdk8s-argocd-test-deployment-c8675cda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - image: registry.cloudticon.com/cdk8s-argocd-test:6f2c49e2710078b251db56f6d29d221b791381e4
          name: hello-kubernetes
          ports:
            - containerPort: 8080
